### ISSUE TITLE
Nitpick: redirect https://grafana.traitcapture.org -> http://grafana.traitcapture.org

### ISSUE THREAD

**Issue by kdmurray91** [appf-anu/tickets#649]
yes, i'm an idiot user, but I was confused why the server disappeared when using https.

**Comment by gdunstone** [comment]
Ok. I'll do this when I get back in.

It caused huge issues with hsts historically

**Comment by gdunstone** [comment]
the problem with this is that grafana is no longer running behind nginx.

**Comment by gdunstone** [comment]
also this isnt the correct place for this. I dont know where is but it isn't here. This repo is mostly automated tickets.

**Comment by gdunstone** [comment]
wontfix
