### ISSUE TITLE
[CRITICAL] GC03L-camera deadman

### ISSUE THREAD

**Issue by gdunstone** [appf-anu/tickets#9]
[OFF] Camera GC03L is OFFLINE.

**Comment by gdunstone** [comment]
this is some weird memory issue that im currently working on

**Comment by zarlo** [comment]
a quote from kapacitor "[OK] Camera GC03L is ONLINE." at 14:30

**Comment by gdunstone** [comment]
I think this is fixed. If it comes up again its not.
